// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChVosBd9_aIcbmDZQ-9b-HAMfHz86dh28',
    appId: '1:758857412073:web:e12f55e6207e677ad62f78',
    messagingSenderId: '758857412073',
    projectId: 'live-chat-9dd49',
    authDomain: 'live-chat-9dd49.firebaseapp.com',
    storageBucket: 'live-chat-9dd49.appspot.com',
    measurementId: 'G-0JD291MYN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx_eIy5TmgTCo-NjopoHpXvMvrChRPKH8',
    appId: '1:758857412073:android:07344944b00bcf01d62f78',
    messagingSenderId: '758857412073',
    projectId: 'live-chat-9dd49',
    storageBucket: 'live-chat-9dd49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb5TyaQfOD6UK0zHp--Tqu3btD0_-2VR8',
    appId: '1:758857412073:ios:21de49628897f8f7d62f78',
    messagingSenderId: '758857412073',
    projectId: 'live-chat-9dd49',
    storageBucket: 'live-chat-9dd49.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
