// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-YBRc3XghUnBzO3exjFFRLC-KX8JNWJY',
    appId: '1:745569949793:web:b8b180ed4b4c657990b220',
    messagingSenderId: '745569949793',
    projectId: 'fir-26385',
    authDomain: 'fir-26385.firebaseapp.com',
    storageBucket: 'fir-26385.appspot.com',
    measurementId: 'G-TQJLQKBZ94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC17Y2RR6GlIfi5Cs6jprSTIiLa17OebKA',
    appId: '1:745569949793:android:85c46d3c38b8644c90b220',
    messagingSenderId: '745569949793',
    projectId: 'fir-26385',
    storageBucket: 'fir-26385.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbalKEaCW7fbJweChthYKyKRiNXm8XZXM',
    appId: '1:745569949793:ios:8bd0e50e9486079490b220',
    messagingSenderId: '745569949793',
    projectId: 'fir-26385',
    storageBucket: 'fir-26385.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
